### ISSUE TITLE
怎么你的air 是16G内存的？

### ISSUE THREAD

**Issue by Ahian** [nabaonan/airbook-6200u-efi#1]

**Comment by nabaonan** [comment]
我的是airbook颜值版，自己加的内存

**Comment by daddycoding** [comment]
我有个自己用的 比较完整的efi 我实际使用没有任何问题
你需要我就发你

**Comment by nabaonan** [comment]
> 的 比较完整的efi 我实际使用没有任何问题
> 你需要我就发

发一下也可以，完美程度是啥样的，什么配置的

**Comment by daddycoding** [comment]
https://github.com/daddycoding/airbook-6200u-efi

**Comment by nabaonan** [comment]
> https://github.com/daddycoding/airbook-6200u-efi

完美了？

**Comment by nabaonan** [comment]
> https://github.com/daddycoding/airbook-6200u-efi

我昨天试了一下你的，进度条到一半就自动重启。也不知道为啥，我的是14.6的系统
