### ISSUE TITLE
帮帮看看这个好装吗 好装的话我就折腾一下 感谢！~

### ISSUE THREAD

**Issue by ghost** [nabaonan/airbook-6200u-efi#10]
电脑型号	Wbin AirBook 笔记本电脑  (扫描时间：2022年03月17日)
操作系统	Windows 10 专业版 64位 ( DirectX 12 )
	
处理器	英特尔 Core i7-6600U @ 2.60GHz 双核
主板	Wbin AirBook ( 6th/7th Generation Intel Processor Family I/O - 9D48 笔记本芯片组 )
内存	8 GB ( 十铨 DDR3L 1600MHz )
主硬盘	建兴 S930 256 ( 256 GB / 固态硬盘 )
主显卡	英特尔 HD Graphics 520 ( 128 MB )
显示器	夏普 SHP1423 LQ133T1JW21 ( 13.3 英寸  )
声卡	英特尔 High Definition Audio 控制器
网卡	瑞昱 RTL810x/8139 Family Fast Ethernet NIC
无线网卡	英特尔 Dual Band Wireless-AC 3165

**Comment by nabaonan** [comment]
> 电脑型号 Wbin AirBook 笔记本电脑 (扫描时间：2022年03月17日) 操作系统 Windows 10 专业版 64位 ( DirectX 12 )
> 
> 处理器 英特尔 Core i7-6600U @ 2.60GHz 双核 主板 Wbin AirBook ( 6th/7th Generation Intel Processor Family I/O - 9D48 笔记本芯片组 ) 内存 8 GB ( 十铨 DDR3L 1600MHz ) 主硬盘 建兴 S930 256 ( 256 GB / 固态硬盘 ) 主显卡 英特尔 HD Graphics 520 ( 128 MB ) 显示器 夏普 SHP1423 LQ133T1JW21 ( 13.3 英寸 ) 声卡 英特尔 High Definition Audio 控制器 网卡 瑞昱 RTL810x/8139 Family Fast Ethernet NIC 无线网卡 英特尔 Dual Band Wireless-AC 3165

看上去可以安装，可以折腾一下

**Comment by nabaonan** [comment]
> 3165

你的网卡是intel，和我的不一样，你要更改无线的驱动，网上搜了一下说是支持，具体需要你自己试试

**Comment by nabaonan** [comment]
@PotatoCo 最近搞了一下，试试这个分支https://github.com/nabaonan/airbook-6200u-efi/tree/6600u-montery
