### ISSUE TITLE
请问一下 还有一个版本是6700U的 是不是替换dsdt就可以完美了？

### ISSUE THREAD

**Issue by hiper25** [nabaonan/airbook-6200u-efi#2]

**Comment by hiper25** [comment]
更正一下 6500U

**Comment by nabaonan** [comment]
> 更正一下 6500U

可以试一下，显卡是一样，替换dsdt试试

**Comment by nabaonan** [comment]
> 更正一下 6500U

上一个issue的是6600u可以正常使用6500u，应该也没问题，先不替换dsdt试试

**Comment by hiper25** [comment]
ok 谢谢啦

**Comment by nabaonan** [comment]
https://github.com/nabaonan/airbook-6200u-efi/issues/4#issuecomment-623852260  @hiper25 这个同学今天用我的可以，他是i7 6600u，据说不改dsdt是可以

**Comment by hiper25** [comment]
> [#4 (comment)](https://github.com/nabaonan/airbook-6200u-efi/issues/4#issuecomment-623852260) @hiper25 这个同学今天用我的可以，他是i7 6600u，据说不改dsdt是可以

现在暂时是完美 睿频啥的 以后追求有时间就追求完美好啦

**Comment by nabaonan** [comment]
> > [#4 (comment)](https://github.com/nabaonan/airbook-6200u-efi/issues/4#issuecomment-623852260) @hiper25 这个同学今天用我的可以，他是i7 6600u，据说不改dsdt是可以
> 
> 
> 
> 现在暂时是完美 睿频啥的 以后追求有时间就追求完美好啦

我这个可以睿频的800到2700

**Comment by nabaonan** [comment]
@hiper25 详细配置发一下

**Comment by nabaonan** [comment]
@hiper25 试试这个分支https://github.com/nabaonan/airbook-6200u-efi/tree/6600u-montery
