### ISSUE TITLE
原装海力士8g没必要注入memory，我删掉后正常识别

### ISSUE THREAD

**Issue by poasdww** [nabaonan/airbook-6200u-efi#3]

**Comment by poasdww** [comment]
原装海力士8g没必要注入memory，我删掉后正常识别

**Comment by poasdww** [comment]
<key>Modules</key>
			<array>
				<dict>
					<key>Frequency</key>
					<integer>1600</integer>
					<key>Size</key>
					<integer>16384</integer>
					<key>Slot</key>
					<integer>0</integer>
					<key>Type</key>
					<string>DDR3</string>
					<key>Vendor</key>
					<string>Micron</string>
				</dict>
删掉这里

**Comment by nabaonan** [comment]
> 没

我以前没升级内存我也没注入，但是升级16g发现不注入启动不了，只能注入，原装内存去掉就行了
