### ISSUE TITLE
你好，请问盒盖睡眠怎么做的，需不需要打dsdt布丁，我在网上搜的dsdt，你的这个没有store方法，用不了，，，谢谢

### ISSUE THREAD

**Issue by poasdww** [nabaonan/airbook-6200u-efi#4]
你好，请问盒盖睡眠怎么做的，需不需要打dsdt布丁，我在网上搜的dsdt，你的这个没有store方法，用不了，，，谢谢

**Comment by poasdww** [comment]
试了很多次，盒盖睡眠和不睡眠2个情况，开机交替出现，比如这次盒盖不睡眠，关机开机（不是重启）后能睡眠，这次盒盖睡眠，关机开机（不是重启）后不能睡眠。可能是nvram变量没初始化之类的？

**Comment by poasdww** [comment]
![屏幕快照 2020-05-02 下午11 49 13](https://user-images.githubusercontent.com/48010799/80868846-8ffc0a80-8ccf-11ea-866f-2cc1a8b8dbf9.png)
看控制台，错误在这

**Comment by nabaonan** [comment]
> 试了很多次，盒盖睡眠和不睡眠2个情况，开机交替出现，比如这次盒盖不睡眠，关机开机（或重启）后能睡眠，这次盒盖睡眠，关机开机（或重启）后不能睡眠。可能是什么变量没初始化？

确实存在这个问题，我也发现了，暂时不确定是哪里导致的，你现在是怎么解决的呢？

**Comment by poasdww** [comment]
> > 试了很多次，盒盖睡眠和不睡眠2个情况，开机交替出现，比如这次盒盖不睡眠，关机开机（或重启）后能睡眠，这次盒盖睡眠，关机开机（或重启）后不能睡眠。可能是什么变量没初始化？
> 
> 确实存在这个问题，我也发现了，暂时不确定是哪里导致的，你现在是怎么解决的呢？

，，，这玩意会损坏电脑，是ec控制器的原因，我找了几个方案，改了dsdt，，，ec芯片还是bios芯片搞坏了，，，

**Comment by poasdww** [comment]
黑苹果谨慎

**Comment by poasdww** [comment]
现在开不了机，等编程器刷bios试试，，，

**Comment by poasdww** [comment]
原始dsdt有h_ec，对比了一下你的dsdt，发现有change h_ec to ec补丁，我用的原始我怀疑是change h_ec to ec补丁导致的，但是这样说不通好坏交替出现，dsdt有储存功能？我不清楚这些，，，但是会损坏笔记本是真的，，，

**Comment by poasdww** [comment]
哈哈哈，我笔记本复活了！！！

**Comment by nabaonan** [comment]
> 原始dsdt有h_ec，对比了一下你的dsdt，发现有change h_ec to ec补丁，我用的原始我怀疑是change h_ec to ec补丁导致的，但是这样说不通好坏交替出现，dsdt有储存功能？我不清楚这些，，，但是会损坏笔记本是真的，，，

确实我这个dsdt之前是加过一些补丁，我一直用着没事啊，都可以启动，你用原始dsdt导致启动不了是吧？

**Comment by poasdww** [comment]
> > 原始dsdt有h_ec，对比了一下你的dsdt，发现有change h_ec to ec补丁，我用的原始我怀疑是change h_ec to ec补丁导致的，但是这样说不通好坏交替出现，dsdt有储存功能？我不清楚这些，，，但是会损坏笔记本是真的，，，
> 
> 确实我这个dsdt之前是加过一些补丁，我一直用着没事啊，都可以启动，你用原始dsdt导致启动不了是吧？

对，你的没问题

**Comment by poasdww** [comment]
确定是ec的问题了，我改的dsdt的ec好像是macos原生控制的变量，导致ec芯片损坏，现在我插电池开不了机，必须断开电池用电源才行，，，

**Comment by poasdww** [comment]
> > 原始dsdt有h_ec，对比了一下你的dsdt，发现有change h_ec to ec补丁，我用的原始我怀疑是change h_ec to ec补丁导致的，但是这样说不通好坏交替出现，dsdt有储存功能？我不清楚这些，，，但是会损坏笔记本是真的，，，
> 
> 确实我这个dsdt之前是加过一些补丁，我一直用着没事啊，都可以启动，你用原始dsdt导致启动不了是吧？

我的意思是合盖睡眠功能应该在   EC/H_EC/EC0和LID0   方法里，改了EC/H_EC会对这个功能产生很明显的影响，但是不能乱试，因为可能损坏硬件

**Comment by nabaonan** [comment]
@light0199 最近发现acpi battery manager1.81.4 会影响到盒盖睡眠，我现在换smc battery manager可以盒盖睡眠，系统是12
