### ISSUE TITLE
CPU6500U GPUHD520 要不要折腾一下？ 

### ISSUE THREAD

**Issue by lucifnce** [nabaonan/airbook-6200u-efi#5]
电脑型号	Wbin Airbook 笔记本电脑  (扫描时间：2020年10月05日)
操作系统	Windows 10 Enterprise 64位 ( DirectX 12 )
	
处理器	英特尔 Core i7-6500U @ 2.50GHz 双核
主板	Wbin Airbook ( 6th/7th Generation Intel Processor Family I/O - 9D48 笔记本芯片组 )
内存	8 GB ( 威刚 DDR3L 1600MHz )
主硬盘	 Netac SSD 512GB ( 507 GB / 固态硬盘 )
主显卡	英特尔 HD Graphics 520 ( 128 MB )
显示器	京东方 BOE0669 ( 13.3 英寸  )
声卡	英特尔 High Definition Audio 控制器
网卡	瑞昱 RTL810x/8139 Family Fast Ethernet NIC

这个配置的 能帮忙折腾一下麽？

**Comment by nabaonan** [comment]
> 电脑型号 Wbin Airbook 笔记本电脑 (扫描时间：2020年10月05日)
> 操作系统 Windows 10 Enterprise 64位 ( DirectX 12 )
> 
> 处理器 英特尔 Core i7-6500U @ 2.50GHz 双核
> 主板 Wbin Airbook ( 6th/7th Generation Intel Processor Family I/O - 9D48 笔记本芯片组 )
> 内存 8 GB ( 威刚 DDR3L 1600MHz )
> 主硬盘 Netac SSD 512GB ( 507 GB / 固态硬盘 )
> 主显卡 英特尔 HD Graphics 520 ( 128 MB )
> 显示器 京东方 BOE0669 ( 13.3 英寸 )
> 声卡 英特尔 High Definition Audio 控制器
> 网卡 瑞昱 RTL810x/8139 Family Fast Ethernet NIC
> 
> 这个配置的 能帮忙折腾一下麽？

试试，直接用不了吗

**Comment by nabaonan** [comment]
没有相关设备，暂时不支持

**Comment by nabaonan** [comment]
> 电脑型号 Wbin Airbook 笔记本电脑 (扫描时间：2020年10月05日)
> 操作系统 Windows 10 Enterprise 64位 ( DirectX 12 )
> 
> 处理器 英特尔 Core i7-6500U @ 2.50GHz 双核
> 主板 Wbin Airbook ( 6th/7th Generation Intel Processor Family I/O - 9D48 笔记本芯片组 )
> 内存 8 GB ( 威刚 DDR3L 1600MHz )
> 主硬盘 Netac SSD 512GB ( 507 GB / 固态硬盘 )
> 主显卡 英特尔 HD Graphics 520 ( 128 MB )
> 显示器 京东方 BOE0669 ( 13.3 英寸 )
> 声卡 英特尔 High Definition Audio 控制器
> 网卡 瑞昱 RTL810x/8139 Family Fast Ethernet NIC
> 
> 这个配置的 能帮忙折腾一下麽？

这两天搞了oc版本，要不要试试？ @lucifnce

**Comment by nabaonan** [comment]
@lucifnce 无线网卡是啥型号

**Comment by lucifnce** [comment]
英特尔 Dual Band Wireless AC 3160

**Comment by lucifnce** [comment]
> @lucifnce 无线网卡是啥型号

英特尔 Dual Band Wireless AC 3160

**Comment by nabaonan** [comment]
> > @lucifnce 无线网卡是啥型号
> 
> 英特尔 Dual Band Wireless AC 3160

https://github.com/nabaonan/airbook-6200u-efi/tree/6600u-montery   这个分支，试试
