### ISSUE TITLE
外接DVI显示器锁屏睡眠后无信号的问题解决

### ISSUE THREAD

**Issue by zhaoest** [nabaonan/airbook-6200u-efi#6]
boot-args igfxonln=1

**Comment by nabaonan** [comment]
> boot-args igfxonln=1

miniHDMI转的dvi？是睡眠唤醒之后外接的显示器就不显示了？是bigsur版本还是哪个版本？

**Comment by zhaoest** [comment]
> > boot-args igfxonln=1
> 
> miniHDMI转的dvi？是睡眠唤醒之后外接的显示器就不显示了？是bigsur版本还是哪个版本？

对的，本来以为是线的问题，加上这个参数就解决了。bigsur11.5.1  oc7.2，刚才白嫖了你最新的EFI

**Comment by nabaonan** [comment]
> 最新

我刚退回到10.14，试了下睡眠好像是有这个问题，我在测测

**Comment by nabaonan** [comment]
已经修复
