### ISSUE TITLE
老哥，能帮忙看一下我的EFI吗？

### ISSUE THREAD

**Issue by Guanhang** [nabaonan/airbook-6200u-efi#7]
我自己做的，相同的CPU，基本能用，就是苹果账号不能登入，还有能优化一下config吗？

**Comment by nabaonan** [comment]
> 我自己做的，相同的CPU，基本能用，就是苹果账号不能登入，还有能优化一下config吗？

换三码吧

**Comment by nabaonan** [comment]
> 我自己做的，相同的CPU，基本能用，就是苹果账号不能登入，还有能优化一下config吗？

你的是airbook？

**Comment by Guanhang** [comment]
不是，我是联想小新

**Comment by nabaonan** [comment]
> 不是，我是联想小新

更换三码在尝试下

**Comment by Guanhang** [comment]
不行,试了好几次都不行

**Comment by nabaonan** [comment]
> 不行,试了好几次都不行

那只能试试别人做的efi好使不好使，没准需要定制什么特别的东西，感觉小新的efi挺多的

**Comment by nabaonan** [comment]
@Guanhang 发下具体鲁大师配置

**Comment by Guanhang** [comment]
![屏幕截图 2022-05-02 215203](https://user-images.githubusercontent.com/12904724/166399530-9dfd03db-2030-4e63-b2c1-bf25e1908970.png)

**Comment by nabaonan** [comment]
> ![屏幕截图 2022-05-02 215203](https://user-images.githubusercontent.com/12904724/166399530-9dfd03db-2030-4e63-b2c1-bf25e1908970.png)

配置基本一样，感觉登录不上苹果账号可能就跟三码有关系吧

**Comment by Guanhang** [comment]
黑苹果的尽头就是白苹果，已经上白苹果了，哈哈哈哈
