### ISSUE TITLE
锁屏睡眠超过几分钟后蓝牙鼠标自动断开连接，需要重启才能重新连接，请问这个怎么解决？一直没找到方案。

### ISSUE THREAD

**Issue by zhaoest** [nabaonan/airbook-6200u-efi#8]
还有请教个问题，11.5想小升级或者直接升级12.0应该怎么操作？直接用系统升级，还是重新烧录镜像安装？

**Comment by nabaonan** [comment]
> 还有请教个问题，11.5想小升级或者直接升级12.0应该怎么操作？直接用系统升级，还是重新烧录镜像安装？

直接ota升级，不用重新做镜像
