### ISSUE TITLE
Monterey，12.2，最新的EFI，电池图标一直不显示闪电。

### ISSUE THREAD

**Issue by zhaoest** [nabaonan/airbook-6200u-efi#9]
电源状态也是电池。关机，或者电池启动再插电源，都不显示。

**Comment by nabaonan** [comment]
> 电源状态也是电池。关机，或者电池启动再插电源，都不显示。

大概之前也遇到过，插电开机电池正常吧

**Comment by nabaonan** [comment]
> 电源状态也是电池。关机，或者电池启动再插电源，都不显示。

你清除缓存再试，清除缓存，关机停留3分钟后再试，电池应该会显示，只是用电池启动有时候插电就不显示闪电吧？

**Comment by zhaoest** [comment]
完美解决！！！之前11.6遇到蓝牙鼠标老断开的问题也没了。

**Comment by zhaoest** [comment]
目前的情况是，按照你说的，我第一次操作，重新开机是好的，闪电显示。然后就再也不行，清除缓存，关机，等5分钟，开机也不显示。我用的hackintool删除的缓存，Library/Caches文件夹也删除过。现在不知道从哪儿下手。

**Comment by nabaonan** [comment]
> 

用的是我的efi吧？所有驱动你看看是不是最新的，如果不是，就更新驱动到最新，清除nvram，清除kext缓存，关机停留3分钟，在开机，插电开机

**Comment by zhaoest** [comment]
用的你最新的EFI。折腾了一下午，kext升级了，缓存啥的也清了，关机至少等10分钟，就是不行。还是太菜，不知道那儿不对。我看你之前说是因为AppleALC这个影响的，我现在显示的是1.6.8，升级到1.6.9还是不显示闪电。能把你现在的最新的EFI发我邮箱吗？或者更新到仓库。

**Comment by nabaonan** [comment]
> 用的你最新的EFI。折腾了一下午，kext升级了，缓存啥的也清了，关机至少等10分钟，就是不行。还是太菜，不知道那儿不对。我看你之前说是因为AppleALC这个影响的，我现在显示的是1.6.8，升级到1.6.9还是不显示闪电。能把你现在的最新的EFI发我邮箱吗？或者更新到仓库。

现在GitHub就是最新的efi，不显示闪电我有个原因是要把PS2controller版本锁定到2.2.4不要更新到最新的

**Comment by zhaoest** [comment]
> > 用的你最新的EFI。折腾了一下午，kext升级了，缓存啥的也清了，关机至少等10分钟，就是不行。还是太菜，不知道那儿不对。我看你之前说是因为AppleALC这个影响的，我现在显示的是1.6.8，升级到1.6.9还是不显示闪电。能把你现在的最新的EFI发我邮箱吗？或者更新到仓库。
> 
> 现在GitHub就是最新的efi，不显示闪电我有个原因是要把PS2controller版本锁定到2.2.4不要更新到最新的

感谢分享，我再研究下。昨晚再用你仓库的efi，然后在occ里面更新驱动，勾选完点击下载，底部提示已更新到某个路径，没更新PS2，保存，然后用kext utility清除了一下，关机，等5分钟，开机的时候选择清除nvram（菜单左边那个SIP显示开启状态），再开机，进去还是不显示闪电。p.s.我用U盘装完12系统以后OTA升级到了12.2.1，不知道这个有没有影响。

**Comment by nabaonan** [comment]
> > > 用的你最新的EFI。折腾了一下午，kext升级了，缓存啥的也清了，关机至少等10分钟，就是不行。还是太菜，不知道那儿不对。我看你之前说是因为AppleALC这个影响的，我现在显示的是1.6.8，升级到1.6.9还是不显示闪电。能把你现在的最新的EFI发我邮箱吗？或者更新到仓库。
> > 
> > 现在GitHub就是最新的efi，不显示闪电我有个原因是要把PS2controller版本锁定到2.2.4不要更新到最新的
> 
> 感谢分享，我再研究下。昨晚再用你仓库的efi，然后在occ里面更新驱动，勾选完点击下载，底部提示已更新到某个路径，没更新PS2，保存，然后用kext utility清除了一下，关机，等5分钟，开机的时候选择清除nvram（菜单左边那个SIP显示开启状态），再开机，进去还是不显示闪电。p.s.我用U盘装完12系统以后OTA升级到了12.2.1，不知道这个有没有影响。

这个问题我有时候也遇到，有时候重启几次就有了

**Comment by zhaoest** [comment]
我折腾电源主要是因为，装系统的时候选择文件保险箱，第一次有电源的时候，自动开始加密，然后电池供电的时候一直提示需要电源才能继续，想用时间机器又提示没加密完成，在淘宝找的安装黑苹果驱动的商家远程折腾也没解决。最后，把那个电池驱动删了，开机就直接电源了，现在相当于台式机的感觉，但是电池还能继续用，不影响，看电量就用指示灯就行。

**Comment by nabaonan** [comment]
> 

6代u我就没遇到这么奇葩的问题，你换个卖家问问

**Comment by nabaonan** [comment]
@zhaoest 最近遇到不显示闪电的问题，acpi battery 1.90就会出现这个问题，smc battery就不会出现，开启-v模式就可以，

**Comment by zhaoest** [comment]
> 

刚才试了下，真的显示闪电了，哈哈哈，大佬牛逼~
